### ISSUE TITLE
Cool concept

### ISSUE THREAD

**Issue by qiubee** [Zeijls/real-time-web-1920#1]
Als ik je concept een beetje begrijp wil je dat gebruikers nummers gaan raden die van Spotify komen. Heel leuk concept! Het is misschien fijner om in de readme de feature eerst uit te leggen en daarna de technische aspecten, want ik moest eerst een beetje zoeken naar wat het concept was.

Een paar dingen die voor mij nog onduidelijk waren:
* ZIjn de nummers compleet willekeurig of zijn ze gebaseerd op de nummers van de gebruiker die als eerst een room start?
* Wat gebeurt er als er meerdere spelers dezelfde score hebben aan het eind?
* Kun je ook zonder Spotify account het spel spelen (als de nummers niet gebaseerd zijn op een Spotify gebruiker)?

**Paar ideeen:**
1. Je kunt er ook een gamechat van maken. Je ziet de 4 antwoorden en je kunt daar op klikken, maar als je een chat hebt, kun je ook gelijk praten over wat je van het nummer vond.
2. Je kunt op het eind nog laten zien welke nummers er voorbij zijn gekomen en ze de mogelijkheid geven om er een playlist van te maken.
3. Meet de tijd wanneer een speler het antwoord heeft gegeven en baseer daar de score op, zodat niemand dezelfde score zal hebben (Kahoot.it).

**Comment by Zeijls** [comment]
Thanks, heb het aangepast, en ga er naar kijken
