### ISSUE TITLE
Data Life Cycle nog niet compleet

### ISSUE THREAD

**Issue by qiubee** [Zeijls/real-time-web-1920#2]
Ik vind de [Data Life Cycle](https://github.com/Zeijls/real-time-web-1920#data-life-cycle) een beetje verwarrend. De flow gaat van links naar rechts en naar beneden. Het wordt misschien makkelijker te begrijpen als je [de componenten meer uit elkaar haalt](https://github.com/aaraar/real-time-web-1920/blob/master/docs/dlc.png) en met [(gekleurde) pijltjes neerzet welke data naar welke component gaat](https://github.com/Mokerstier/real-time-web-1920/blob/b247101cb3a9a2dccb0ff761afe5fe6046aefb58/repo-img/DLC-instagraff.png) en wat ermee gebeurt. Ook mist er nog hoe de data eruit ziet op de server en van de API.

**Comment by Zeijls** [comment]
Klopt, heb het aangepast thanks
